export const AUTHORIZED = 'authorized'
export const UNAUTHORIZED = 'unauthorized'
export const BLOCKED = 'blocked'
export const DELETED = 'deleted'
export const AUTH_ACTION_SUCCESS = 'authActionSuccess'
export const AUTH_ACTION_ERROR = 'authActionError'
export const AUTH_HEADER = 'x-authorization'
